Repository OpenVoiceOS/ovos-skill-weather, pull requests merged in 2023-05, with the labels that each got.

#36 Add version automation
  .github/workflows/auto_translate.yml
  .github/workflows/coverage.yml
  .github/workflows/publish_alpha.yml
  .github/workflows/publish_build.yml
  .github/workflows/publish_major.yml
  .github/workflows/publish_minor.yml
  .gitignore
  scripts/bump_alpha.py
  scripts/bump_build.py
  scripts/bump_major.py
  scripts/bump_minor.py
  scripts/remove_alpha.py
  setup.py
  test/unittests/__init__.py
  version.py
Labels: automations

#39 add back translate workflow
  .github/workflows/auto_translate.yml
  .github/workflows/propose_translation.yml
  .github/workflows/publish_alpha.yml
  .github/workflows/unit_tests.yml
  locale/es-es/dialog/condition/ash.dialog
  locale/es-es/dialog/condition/clear.dialog
  locale/es-es/dialog/condition/clouds.dialog
  locale/es-es/dialog/condition/drizzle.dialog
  locale/es-es/dialog/condition/dust.dialog
  locale/es-es/dialog/condition/haze.dialog
  locale/es-es/dialog/condition/humidity.dialog
  locale/es-es/dialog/condition/mist.dialog
  locale/es-es/dialog/condition/rain.dialog
  locale/es-es/dialog/condition/smoke.dialog
  locale/es-es/dialog/condition/snow.dialog
  locale/es-es/dialog/condition/squall.dialog
  locale/es-es/dialog/condition/thunderstorm.dialog
  locale/es-es/dialog/condition/tornado.dialog
  locale/es-es/dialog/current/current-weather-local.dialog
  locale/es-es/dialog/current/current-weather-location.dialog
  locale/es-es/dialog/daily/daily-weather-local.dialog
  locale/es-es/dialog/daily/daily-weather-location.dialog
  locale/es-es/dialog/direction/east.dialog
  locale/es-es/dialog/direction/north.dialog
  locale/es-es/dialog/direction/northeast.dialog
  locale/es-es/dialog/direction/northwest.dialog
  locale/es-es/dialog/direction/south.dialog
  locale/es-es/dialog/direction/southeast.dialog
  locale/es-es/dialog/direction/southwest.dialog
  locale/es-es/dialog/direction/west.dialog
  locale/es-es/dialog/error/location-not-found.dialog
  locale/es-es/dialog/hourly/hourly-weather-local.dialog
  locale/es-es/dialog/hourly/hourly-weather-location.dialog
  locale/es-es/dialog/percentage-number.dialog
  locale/es-es/dialog/unit/celsius.dialog
  locale/es-es/dialog/unit/fahrenheit.dialog
  locale/es-es/dialog/unit/meters per second.dialog
  locale/es-es/dialog/unit/miles per hour.dialog
  locale/es-es/regex/location.rx
  locale/es-es/vocabulary/condition/humidity.voc
  locale/es-es/vocabulary/condition/precipitation.voc
  locale/es-es/vocabulary/condition/windy.voc
  locale/es-es/vocabulary/date-time/later.voc
  locale/es-es/vocabulary/date-time/next.voc
  locale/es-es/vocabulary/forecast.voc
  locale/es-es/vocabulary/location.voc
  locale/es-es/vocabulary/query/query.voc
  locale/es-es/vocabulary/sunrise.voc
  locale/es-es/vocabulary/sunset.voc
  locale/es-es/vocabulary/weather.voc
  scripts/translate.py
Labels: automations, translation

#43 fix de-de entities
  locale/de-de/dialog/current/current-weather-location.dialog
  locale/de-de/dialog/current/current-wind-light-local.dialog
  locale/de-de/dialog/current/current-wind-light-location.dialog
  locale/de-de/dialog/current/current-wind-moderate-local.dialog
  locale/de-de/dialog/current/current-wind-moderate-location.dialog
  locale/de-de/dialog/current/current-wind-strong-local.dialog
  locale/de-de/dialog/current/current-wind-strong-location.dialog
  locale/de-de/dialog/current/currrent-clouds-alternative-local.dialog
  locale/de-de/dialog/daily/daily-condition-expected-local.dialog
  locale/de-de/dialog/daily/daily-weather-location.dialog
  locale/de-de/dialog/daily/daily-wind-light-local.dialog
  locale/de-de/dialog/daily/daily-wind-light-location.dialog
  locale/de-de/dialog/daily/daily-wind-moderate-local.dialog
  locale/de-de/dialog/daily/daily-wind-moderate-location.dialog
  locale/de-de/dialog/daily/daily-wind-strong-local.dialog
  locale/de-de/dialog/daily/daily-wind-strong-location.dialog
  locale/de-de/dialog/error/forty-eight-hours-available.dialog
  locale/de-de/dialog/error/location-not-found.dialog
  locale/de-de/dialog/error/seven-days-available.dialog
  locale/de-de/dialog/hourly/hourly-precipitation-next-local.dialog
  locale/de-de/dialog/hourly/hourly-precipitation-next-location.dialog
  locale/de-de/dialog/hourly/hourly-temperature-location.dialog
  locale/de-de/vocabulary/condition/do-i-need-an-umbrella.intent
  locale/de-de/vocabulary/condition/do.i.need.an.umbrella.intent
Labels: translation

#42 feat/OpenMeteo
  README.md
  __init__.py
  requirements.txt
  setup.py
  skill/api.py
  skill/ovosapiservice.py
  skill/weather.py
  test/unittests/test_skill_loading.py
  weather_helpers/__init__.py
  weather_helpers/config.py
  weather_helpers/dialog.py
  weather_helpers/intent.py
  weather_helpers/openmeteo.py
  weather_helpers/util.py
  weather_helpers/weather.py
Labels: enhancement
